import type { ServiceOfferCardProps } from "@/components/ui/ServiceOfferCard";

export const homeServices: Omit<ServiceOfferCardProps, "delay">[] = [
  {
    icon: "🛒",
    title: "Shopify Development",
    problem: "Low conversion, slow storefronts, and limited customization block ecommerce growth.",
    solution: "Custom Shopify Plus stores, CRO-focused themes, checkout optimization, and integrations.",
    value: "Higher revenue per visitor, faster launches, and scalable ecommerce operations.",
    href: "/services/shopify-development",
    ctaLabel: "Shopify services",
    accent: "#95BF47",
  },
  {
    icon: "🤖",
    title: "AI Automation",
    problem: "Manual workflows drain time and customer support costs keep rising.",
    solution: "AI chatbots, CRM automation, workflow bots, and intelligent business process automation.",
    value: "24/7 support, faster lead response, and lower operational overhead.",
    href: "/services/ai-business-automation",
    ctaLabel: "AI automation",
    accent: "#00f2ff",
  },
  {
    icon: "☁️",
    title: "SaaS Development",
    problem: "Startups need MVPs fast but lack engineering capacity for dashboards and billing.",
    solution: "SaaS MVPs, admin panels, subscription systems, analytics dashboards, and APIs.",
    value: "Ship faster, validate product-market fit, and scale recurring revenue.",
    href: "/services/saas-development",
    ctaLabel: "SaaS development",
    accent: "#7c3aed",
  },
  {
    icon: "🏪",
    title: "Marketplace Development",
    problem: "Two-sided platforms are complex — vendors, buyers, payments, and trust at scale.",
    solution: "Multi-vendor marketplaces with vendor dashboards, order flows, and payment-ready architecture.",
    value: "Launch faster with proven marketplace patterns and growth-ready infrastructure.",
    href: "/services/marketplace-development",
    ctaLabel: "Marketplace builds",
    accent: "#c026d3",
  },
  {
    icon: "💻",
    title: "Web Applications",
    problem: "Off-the-shelf tools don't match unique business workflows and performance needs.",
    solution: "Custom web apps, modern stacks, UI/UX design, and performance-optimized architecture.",
    value: "Tailored software that improves efficiency and supports long-term growth.",
    href: "/services/web-application-development",
    ctaLabel: "Web development",
    accent: "#38bdf8",
  },
  {
    icon: "💬",
    title: "AI Chatbots",
    problem: "Customers expect instant answers but human teams can't scale 24/7.",
    solution: "Custom AI chatbots for sales, support, and lead qualification with CRM integration.",
    value: "More qualified leads, happier customers, and measurable support savings.",
    href: "/services/ai-chatbot-development",
    ctaLabel: "Chatbot development",
    accent: "#34d399",
  },
];

export const solutionBlocks = [
  {
    id: "ecommerce",
    icon: "🛍️",
    title: "For ecommerce businesses",
    items: [
      "Shopify development & Shopify Plus",
      "Conversion rate optimization",
      "Product page & checkout improvement",
      "Store speed & technical SEO",
    ],
    href: "/services/shopify-development",
    accent: "#95BF47",
  },
  {
    id: "automation",
    icon: "⚡",
    title: "For business automation",
    items: [
      "AI chatbots & virtual assistants",
      "CRM & workflow automation",
      "Customer support automation",
      "Lead qualification bots",
    ],
    href: "/services/ai-business-automation",
    accent: "#00f2ff",
  },
  {
    id: "startups",
    icon: "🚀",
    title: "For startups",
    items: [
      "SaaS MVP development",
      "Admin panels & dashboards",
      "Subscription & billing systems",
      "Product analytics & growth tools",
    ],
    href: "/services/saas-development",
    accent: "#7c3aed",
  },
  {
    id: "marketplaces",
    icon: "🌐",
    title: "For marketplaces",
    items: [
      "Vendor & seller dashboards",
      "Buyer/seller workflow design",
      "Payment-ready architecture",
      "Trust, reviews & dispute flows",
    ],
    href: "/services/marketplace-development",
    accent: "#c026d3",
  },
];
