import type { ServiceOfferCardProps } from "@/components/ui/ServiceOfferCard";

/** Homepage services — priority order per product spec */
export const homeServices: Omit<ServiceOfferCardProps, "delay">[] = [
  {
    icon: "🛒",
    title: "Shopify Development",
    problem: "Generic themes and slow stores limit revenue and brand differentiation.",
    solution: "Custom Shopify & Shopify Plus builds with CRO, speed optimization, and integrations.",
    value: "Higher conversions, faster launches, and ecommerce that scales.",
    href: "/services/shopify-development",
    ctaLabel: "Shopify development",
    accent: "#95BF47",
  },
  {
    icon: "💬",
    title: "AI Chatbots",
    problem: "Customers expect instant answers; support teams can't scale 24/7.",
    solution: "Custom AI chatbots for sales, support, and lead qualification with CRM sync.",
    value: "More leads, lower support costs, happier customers.",
    href: "/services/ai-chatbot-development",
    ctaLabel: "AI chatbots",
    accent: "#34d399",
  },
  {
    icon: "💻",
    title: "Website Development",
    problem: "Outdated sites hurt trust, SEO, and conversion on every channel.",
    solution: "Modern, fast websites and web apps with premium UI and technical SEO.",
    value: "Professional brand presence that converts visitors into clients.",
    href: "/services/web-application-development",
    ctaLabel: "Web development",
    accent: "#38bdf8",
  },
  {
    icon: "⚙️",
    title: "Automation Systems",
    problem: "Manual workflows waste hours and create costly errors across teams.",
    solution: "AI-powered automation for CRM, support, operations, and internal processes.",
    value: "Save time, reduce errors, and scale operations without hiring.",
    href: "/services/ai-business-automation",
    ctaLabel: "Automation systems",
    accent: "#00f2ff",
  },
  {
    icon: "☁️",
    title: "SaaS Development",
    problem: "Startups need MVPs fast but lack capacity for billing, dashboards, and APIs.",
    solution: "Full SaaS builds — MVPs, admin panels, subscriptions, and analytics.",
    value: "Ship faster, validate PMF, and grow recurring revenue.",
    href: "/services/saas-development",
    ctaLabel: "SaaS development",
    accent: "#7c3aed",
  },
  {
    icon: "🎯",
    title: "Landing Pages",
    problem: "Campaign traffic lands on weak pages that fail to capture leads.",
    solution: "High-converting landing pages with premium design, A/B-ready structure, and SEO.",
    value: "More leads per ad dollar and campaigns that actually convert.",
    href: "/contact",
    ctaLabel: "Get a landing page",
    accent: "#f472b6",
  },
];
