export const serviceCategories = [
  {
    id: "websites",
    icon: "🌐",
    title: "Websites",
    desc: "Corporate sites, landing pages, and web apps with modern stacks.",
    tech: ["Next.js", "React", "WordPress"],
    timeline: "2–8 weeks",
    price: "$2k – $25k",
  },
  {
    id: "ecommerce",
    icon: "🛒",
    title: "E-commerce",
    desc: "Shopify, WooCommerce, and custom storefronts with payments.",
    tech: ["Shopify", "Stripe", "Headless"],
    timeline: "4–12 weeks",
    price: "$5k – $50k",
  },
  {
    id: "ai",
    icon: "🤖",
    title: "AI Automation",
    desc: "Agents, workflows, CRM sync, and intelligent operations.",
    tech: ["OpenAI", "LangChain", "n8n"],
    timeline: "2–6 weeks",
    price: "$3k – $40k",
  },
  {
    id: "bots",
    icon: "⚡",
    title: "Bots",
    desc: "Telegram, Discord, and support bots with integrations.",
    tech: ["Node.js", "Python", "APIs"],
    timeline: "1–4 weeks",
    price: "$1k – $15k",
  },
  {
    id: "saas",
    icon: "☁️",
    title: "SaaS",
    desc: "Multi-tenant platforms, dashboards, and subscription billing.",
    tech: ["Next.js", "PostgreSQL", "Auth"],
    timeline: "8–20 weeks",
    price: "$15k – $120k",
  },
  {
    id: "mobile",
    icon: "📱",
    title: "Mobile Apps",
    desc: "iOS, Android, and cross-platform product builds.",
    tech: ["React Native", "Flutter", "Swift"],
    timeline: "6–16 weeks",
    price: "$10k – $80k",
  },
  {
    id: "uiux",
    icon: "✨",
    title: "UI/UX",
    desc: "Product design, design systems, and high-fidelity prototypes.",
    tech: ["Figma", "Framer", "Design tokens"],
    timeline: "2–8 weeks",
    price: "$2k – $30k",
  },
  {
    id: "branding",
    icon: "🎨",
    title: "Branding",
    desc: "Identity, logos, and brand guidelines for digital products.",
    tech: ["Illustrator", "Figma", "Motion"],
    timeline: "2–6 weeks",
    price: "$1.5k – $20k",
  },
  {
    id: "seo",
    icon: "📈",
    title: "SEO",
    desc: "Technical SEO, content strategy, and growth optimization.",
    tech: ["Analytics", "Core Web Vitals", "Content"],
    timeline: "Ongoing",
    price: "$500 – $8k/mo",
  },
  {
    id: "marketing",
    icon: "📣",
    title: "Marketing",
    desc: "Paid ads, funnels, email, and conversion-focused campaigns.",
    tech: ["Meta Ads", "Google", "Email"],
    timeline: "Ongoing",
    price: "$1k – $15k/mo",
  },
];
